# Generated by Django 6.0.5 on 2026-05-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FROZEN", "Frozen"),
                            ("RELEASED", "Released"),
                            ("FORFEITED", "Forfeited"),
                        ],
                        db_index=True,
                        default="FROZEN",
                        max_length=20,
                    ),
                ),
                ("frozen_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
    ]
