# Generated by Django 6.0.5 on 2026-05-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="commission_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="Montant commission",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="host_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="Montant hôte",
            ),
        ),
    ]
