# Generated by Django 6.0.5 on 2026-05-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="id_card_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Numéro de pièce d'identité",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_card_type",
            field=models.CharField(
                choices=[
                    ("CNI", "Carte Nationale d'Identité"),
                    ("PASSPORT", "Passeport"),
                    ("RESIDENCE_PERMIT", "Carte de Séjour"),
                ],
                default="CNI",
                max_length=20,
                verbose_name="Type de pièce d'identité",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_kyc_verified",
            field=models.BooleanField(
                default=False, verbose_name="Vérification KYC effectuée"
            ),
        ),
    ]
