# Generated by Django 6.0.5 on 2026-05-18 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="id_card_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Numéro de pièce d'identité",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_card_type",
            field=models.CharField(
                choices=[
                    ("CNI", "Carte Nationale d'Identité"),
                    ("PASSPORT", "Passeport"),
                    ("RESIDENCE_PERMIT", "Carte de Séjour"),
                ],
                default="CNI",
                max_length=20,
                verbose_name="Type de pièce d'identité",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_kyc_verified",
            field=models.BooleanField(
                default=False, verbose_name="Vérification KYC effectuée"
            ),
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CNI", "Carte Nationale d'Identité"),
                            ("PASSPORT", "Passeport"),
                            ("RESIDENCE_PERMIT", "Carte de Séjour"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to="kyc_documents/", verbose_name="Fichier du document"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("VALIDATED", "Validé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Soumis le"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Revu le"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Raison du rejet"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document KYC",
                "verbose_name_plural": "Documents KYC",
            },
        ),
    ]
