# Generated by Django 6.0.5 on 2026-05-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("TERRAIN", "Terrain"),
                            ("MAISON", "Maison"),
                            ("APPARTEMENT", "Appartement"),
                            ("ESPACE_EVENEMENTIEL", "Espace Événementiel"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ESTUAIRE", "Estuaire"),
                            ("HAUT_OGOQUE", "Haut-Ogooué"),
                            ("MOYEN_OGOQUE", "Moyen-Ogooué"),
                            ("NGCOUNIE", "Ngounié"),
                            ("NYANGA", "Nyanga"),
                            ("OGOQUE_IVINDO", "Ogooué-Ivindo"),
                            ("OGOQUE_LOLO", "Ogooué-Lolo"),
                            ("OGOQUE_MARITIME", "Ogooué-Maritime"),
                            ("WOCLEU_NTEM", "Woleu-Ntem"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
    ]
