# Generated by Django 6.0.5 on 2026-05-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("TERRAIN", "Terrain"),
                            ("MAISON", "Maison"),
                            ("APPARTEMENT", "Appartement"),
                            ("ESPACE_EVENEMENTIEL", "Espace Événementiel"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ESTUAIRE", "Estuaire"),
                            ("HAUT-OGOOUÉ", "Haut-Ogooué"),
                            ("MOYEN-OGOOUÉ", "Moyen-Ogooué"),
                            ("NGOUNIÉ", "Ngounié"),
                            ("NYANGA", "Nyanga"),
                            ("OGOOUÉ-IVINDO", "Ogooué-Ivindo"),
                            ("OGOOUÉ-LOLO", "Ogooué-Lolo"),
                            ("OGOOUÉ-MARITIME", "Ogooué-Maritime"),
                            ("WOLEU-NTEM", "Woleu-Ntem"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
