# Generated by Django 6.0.5 on 2026-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("estuaire", "Estuaire"),
                            ("haut_ogooue", "Haut-Ogooué"),
                            ("moyen_ogooue", "Moyen-Ogooué"),
                            ("ngounie", "Ngounié"),
                            ("nyanga", "Nyanga"),
                            ("ogooue_ivindo", "Ogooué-Ivindo"),
                            ("ogooue_lolo", "Ogooué-Lolo"),
                            ("ogooue_maritime", "Ogooué-Maritime"),
                            ("woleu_ntem", "Woleu-Ntem"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("villa", "Villa"),
                            ("appartement", "Appartement"),
                            ("terrain", "Terrain"),
                            ("espace_evenementiel", "Espace Événementiel"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
    ]
