# Generated by Django 6.0.5 on 2026-05-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="jeedom_api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Clé API Jeedom"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="jeedom_api_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL API Jeedom"),
        ),
        migrations.AddField(
            model_name="property",
            name="lock_command_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ID Commande Verrouillage",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="unlock_command_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ID Commande Déverrouillage",
            ),
        ),
    ]
