# Generated by Django 6.0.5 on 2026-05-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="caution_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
