# Generated by Django 6.0.5 on 2026-05-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="property",
            name="neighborhood",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Quartier"
            ),
        ),
    ]
