# Generated by Django 6.0.5 on 2026-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="province",
            field=models.CharField(
                choices=[
                    ("ESTUAIRE", "Estuaire"),
                    ("HAUT_OGOOUÉ", "Haut-Ogooué"),
                    ("MOYEN_OGOOUÉ", "Moyen-Ogooué"),
                    ("NGOUNIÉ", "Ngounié"),
                    ("NYANGA", "Nyanga"),
                    ("OGOOUÉ_IVINDO", "Ogooué-Ivindo"),
                    ("OGOOUÉ_LOLO", "Ogooué-Lolo"),
                    ("OGOOUÉ_MARITIME", "Ogooué-Maritime"),
                    ("WOLEU_NTEM", "Woleu-Ntem"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
