# Generated by Django 6.0.5 on 2026-05-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Montant de la caution",
                    ),
                ),
                (
                    "is_frozen",
                    models.BooleanField(default=False, verbose_name="Est gelée"),
                ),
                (
                    "is_released",
                    models.BooleanField(default=False, verbose_name="Est libérée"),
                ),
                (
                    "has_noise_complaint",
                    models.BooleanField(
                        default=False, verbose_name="Tapage nocturne signalé"
                    ),
                ),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caution (Escrow)",
                "verbose_name_plural": "Cautions (Escrow)",
            },
        ),
    ]
