# Generated by Django 6.0.5 on 2026-05-13 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant de la caution",
                    ),
                ),
                ("is_frozen", models.BooleanField(default=True, verbose_name="Gelé")),
                (
                    "is_released",
                    models.BooleanField(default=False, verbose_name="Libéré"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow",
                        to="bookings.booking",
                        verbose_name="Réservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caution (Escrow)",
                "verbose_name_plural": "Cautions (Escrows)",
            },
        ),
    ]
