# Generated by Django 6.0.5 on 2026-05-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escrow",
            name="is_frozen",
        ),
        migrations.RemoveField(
            model_name="escrow",
            name="is_released",
        ),
        migrations.AddField(
            model_name="escrow",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("FROZEN", "Gelée"),
                    ("RELEASED", "Libérée"),
                    ("CLAIMED", "Réclamée (Tapage)"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
